[project]
name = "greqs"
version = "0.1.0"
dependencies = ["importlib_metadata"]
requires-python = ">= 3.8"

[project.scripts]
greqs = "greqs.cli:main"

[tool.pytest.ini_options]
python_files = ["tests.py"]
